2015-02-23 16:39:34	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.crm_activity_type): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 16:39:34	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.crm_activity_type WHERE act_type_code = 'COMPL_MS'): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 16:42:16	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 16:42:16	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN] WHERE act_type_code = 'COMPL_MS'): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 16:44:41	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 16:57:12	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 16:59:46	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories2.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories2.name" could not be bound.] to not exist
2015-02-23 17:01:09	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories2.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories2.name" could not be bound.] to not exist
2015-02-23 17:09:04	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories2.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories2.name" could not be bound.] to not exist
2015-02-23 17:09:51	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_nit.involve_type_desc /*_categories.name*/ FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_nit.involve_type_desc" could not be bound.] to not exist
2015-02-23 17:11:42	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:12:17	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:13:06	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:16:56	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:18:45	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:20:06	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:20:36	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:21:29	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:21:49	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_reference_daily_sales_and_cancellations_entity.uda_132_2922,_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:22:12	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.uda_132_2922,_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:22:42	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.uda_132_2922,_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:22:59	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.uda_132_2922,_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:28:14	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:29:45	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
2015-02-23 17:32:15	FAILED	error executing sourceSQL (SELECT _reference_daily_sales_and_cancellations_entity.[uda_132_2922],_nit.involve_type_desc,_categories.name FROM lumo.[tbl_3_132_EN]): AssertionError: expected [RequestError: The multi-part identifier "_categories.name" could not be bound.] to not exist
